version: '3.8'

services:
  ai-service:
    image: ghcr.io/${GITHUB_USERNAME}/hearrt-ai:${AI_VERSION:-latest}
    container_name: hearrt_ai
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - hearrt_network

networks:
  hearrt_network:
    external: true
