version: '3.8'

services:
  backend:
    image: ghcr.io/${GITHUB_USERNAME}/hearrt-backend:${BACKEND_VERSION:-latest}
    restart: always
    env_file:
      - .env
    ports:
      - "${HOST_PORT:-4000}:8080"
    networks:
      - hearrt_network

networks:
  hearrt_network:
    external: true
